/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { load } from "js-yaml";
import { describe, expect, it } from "vitest";
import { generateManifest, planBuild } from "./manifest";
import {
  BATCH_PROCESSOR,
  FILE_STORAGE,
  FORWARD_CONNECTOR,
  K8S_ATTRIBUTES_PROCESSOR,
  NO_MODULE_RECEIVER,
  OTLP_EXPORTER,
  OTLP_RECEIVER,
  RELEASE_COMPONENTS,
} from "./test-fixtures";

describe("generateManifest", () => {
  it("writes an OCB manifest with sections in pipeline order", () => {
    const manifest = generateManifest({
      name: "otelcol-custom",
      collectorVersion: "0.161.0",
      components: [
        FILE_STORAGE,
        OTLP_EXPORTER,
        K8S_ATTRIBUTES_PROCESSOR,
        FORWARD_CONNECTOR,
        BATCH_PROCESSOR,
        OTLP_RECEIVER,
      ],
    });

    expect(manifest)
      .toBe(`# OpenTelemetry Collector Builder (OCB) manifest, generated by the OpenTelemetry Ecosystem Explorer.
# Build it with OCB v0.161.0: the builder's version sets the Collector core version.
dist:
  name: otelcol-custom
  description: Custom OpenTelemetry Collector distribution
  output_path: ./_build

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.161.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v1.0.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.161.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.161.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.161.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.161.0
`);
  });

  it("parses as YAML with the fields OCB reads", () => {
    const manifest = generateManifest({
      name: "otelcol-custom",
      collectorVersion: "0.161.0",
      components: [OTLP_RECEIVER, OTLP_EXPORTER],
    });

    expect(load(manifest)).toEqual({
      dist: {
        name: "otelcol-custom",
        description: "Custom OpenTelemetry Collector distribution",
        output_path: "./_build",
      },
      receivers: [{ gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.161.0" }],
      exporters: [{ gomod: "go.opentelemetry.io/collector/exporter/otlpexporter v0.161.0" }],
    });
  });

  it("has no otelcol_version, providers, or telemetry", () => {
    const manifest = generateManifest({
      name: "otelcol-custom",
      collectorVersion: "0.161.0",
      components: [OTLP_RECEIVER],
    });

    expect(manifest).not.toMatch(/otelcol_version|providers:|telemetry:/);
  });

  it("skips components without Go module data", () => {
    const manifest = generateManifest({
      name: "otelcol-custom",
      collectorVersion: "0.161.0",
      components: [NO_MODULE_RECEIVER],
    });

    expect(manifest).not.toContain("receivers:");
  });

  it("quotes a name that isn't a valid build name", () => {
    const manifest = generateManifest({
      name: "bad: name",
      collectorVersion: "0.161.0",
      components: [OTLP_RECEIVER],
    });

    expect((load(manifest) as { dist: { name: string } }).dist.name).toBe("bad: name");
  });
});

describe("planBuild", () => {
  it("splits picked IDs into included, unavailable, and missing module data", () => {
    const plan = planBuild(
      [
        "core-otlpexporter",
        "contrib-removedreceiver",
        "contrib-filelogreceiver",
        "core-otlpreceiver",
      ],
      RELEASE_COMPONENTS
    );

    expect(plan.included).toEqual([OTLP_EXPORTER, OTLP_RECEIVER]);
    expect(plan.unavailableIds).toEqual(["contrib-removedreceiver"]);
    expect(plan.missingModule).toEqual([NO_MODULE_RECEIVER]);
  });
});
