/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { isValidBuildName } from "@/hooks/use-collector-build";
import type { IndexComponent } from "@/types/collector";

export const MANIFEST_FILENAME = "builder-config.yaml";

/** Where OCB writes the generated sources and the binary, relative to where it runs. */
export const BUILD_OUTPUT_PATH = "./_build";

/** Manifest sections in Collector pipeline order, with the component type each holds. */
export const MANIFEST_SECTIONS = [
  { type: "receiver", section: "receivers" },
  { type: "processor", section: "processors" },
  { type: "exporter", section: "exporters" },
  { type: "connector", section: "connectors" },
  { type: "extension", section: "extensions" },
] as const;

export interface BuildPlan {
  /** Components the manifest includes. Each has a Go module and version. */
  included: IndexComponent[];
  /** Picked IDs the target release doesn't contain, e.g. removed components. */
  unavailableIds: string[];
  /** Picked components the release contains but without Go module data to write. */
  missingModule: IndexComponent[];
}

/** Resolves the picked component IDs against the components of the target release. */
export function planBuild(
  componentIds: readonly string[],
  releaseComponents: readonly IndexComponent[]
): BuildPlan {
  const byId = new Map(releaseComponents.map((component) => [component.id, component]));
  const plan: BuildPlan = { included: [], unavailableIds: [], missingModule: [] };
  for (const id of componentIds) {
    const component = byId.get(id);
    if (!component) {
      plan.unavailableIds.push(id);
    } else if (!component.go_module || !component.go_module_version) {
      plan.missingModule.push(component);
    } else {
      plan.included.push(component);
    }
  }
  return plan;
}

export interface ManifestOptions {
  /** The distribution's binary name (`dist.name`). */
  name: string;
  /** The Collector release the build targets, without a "v" prefix (e.g. "0.161.0"). */
  collectorVersion: string;
  /** Components to include. Entries without Go module data are skipped. */
  components: readonly IndexComponent[];
}

/**
 * Renders an OCB manifest. It has no `otelcol_version`: OCB dropped that field in v0.113.0,
 * and the Collector core version now comes from the OCB binary itself, which is why the
 * header names the OCB version to build with. `providers` and `telemetry` are omitted so OCB
 * applies its defaults, which match its own version.
 */
export function generateManifest({ name, collectorVersion, components }: ManifestOptions): string {
  const lines = [
    "# OpenTelemetry Collector Builder (OCB) manifest, generated by the OpenTelemetry Ecosystem Explorer.",
    `# Build it with OCB v${collectorVersion}: the builder's version sets the Collector core version.`,
    "dist:",
    // A JSON string is a valid YAML double-quoted scalar, so an unusual name can't break the file.
    `  name: ${isValidBuildName(name) ? name : JSON.stringify(name)}`,
    "  description: Custom OpenTelemetry Collector distribution",
    `  output_path: ${BUILD_OUTPUT_PATH}`,
  ];
  for (const { type, section } of MANIFEST_SECTIONS) {
    const specs = components
      .filter((component) => component.type === type)
      .flatMap((component) =>
        component.go_module && component.go_module_version
          ? [`${component.go_module} ${component.go_module_version}`]
          : []
      )
      .sort();
    if (specs.length > 0) {
      lines.push("", `${section}:`, ...specs.map((spec) => `  - gomod: ${spec}`));
    }
  }
  return `${lines.join("\n")}\n`;
}
